apiVersion: v1
kind: Secret
metadata:
  name: laravel-env-secret
type: Opaque
stringData:
    APP_KEY: base64:5bOkBz1n9EypXub6dLXVIzx/u/hKWBHrkW8Egetv14Y=
    APP_ENV: production
    APP_NAME: laravel
    DB_CONNECTION: mysql
    DB_HOST: mysql
    DB_USERNAME: laravel
    DB_PASSWORD: supersecretpassword
    DB_DATABASE: app_db
    DB_PORT: "3306"
    CACHE_DRIVER: redis
    # QUEUE_DRIVER: sync
    QUEUE_CONNECTION: redis

    REDIS_HOST: redis
    REDIS_PASSWORD: ""
    REDIS_PORT: "6379"
    REDIS_CLIENT: "predis"

    

  